services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - noteboards
    deploy:
      placement:
        constraints:
          - node.labels.role == db

  backend:
    image: ghcr.io/danieljimenezrivares/mern-docker-deployment-backend:main
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/noteboards?authSource=admin"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - noteboards
    deploy:
      placement:
        constraints:
          - node.labels.role == backend

  frontend:
    image: ghcr.io/danieljimenezrivares/mern-docker-deployment-frontend:main
    environment:
      API_BACKEND: "http://backend:4000"
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - noteboards
    deploy:
      placement:
        constraints:
          - node.labels.role == frontend

networks:
  noteboards:

volumes:
  mongo_data: